package com.example.ProjectHibernate;

import java.time.LocalDate;
import java.time.Month;

import org.hibernate.Session;
import org.hibernate.SessionFactory;

import com.example.Entity.Bill;
import com.example.Entity.Doctor;
import com.example.Entity.Patient;
import com.example.Entity.Room;
public class App 
{
    public static void main( String[] args )
    {
    	SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
		Session session = sessionFactory.openSession();
		session.beginTransaction();
		try 
		{
			Doctor doctor=new Doctor();
	        doctor.setDname("P.Chakraborty");
	        doctor.setSpecialist("Cardiologist");
	        Doctor doctor1=new Doctor();
	        doctor1.setDname("A.D.Ghosh");
	        doctor1.setSpecialist("Dermatologist");
	        Doctor doctor2=new Doctor();
	        doctor2.setDname("S.Bose");
	        doctor2.setSpecialist("Neurologist");
	        Doctor doctor3=new Doctor();
	        doctor3.setDname("N.Bhattacharya");
	        doctor3.setSpecialist("Oncologist");
	        Doctor doctor4=new Doctor();
	        doctor4.setDname("K.Samanta");
	        doctor4.setSpecialist("Psychiatrist");
	        Doctor doctor5=new Doctor();
	        doctor5.setDname("P.Chaudhary");
	        doctor5.setSpecialist("Gynecologist");
	        Doctor doctor6=new Doctor();
	        doctor6.setDname("M.Saha");
	        doctor6.setSpecialist("Nephrologist");
	        Doctor doctor7=new Doctor();
	        doctor7.setDname("N.Dutta");
	        doctor7.setSpecialist("Pediatrician");
	        
	        Bill bill=new Bill();
	        Room room=new Room();
	        Patient patient=new Patient();
			bill.setDate(LocalDate.of(2023,Month.NOVEMBER,30));
			bill.setAmount(32000);
			bill.setStatus("Cleared"); 
			room.setType("General");
			room.setStatus("Available");
	        patient.setPname("Priya Chaudhary");
            patient.setAddress("Asansole");
            patient.setMobile("9846773280");
	        patient.setDoctor(doctor1);
			patient.setBill(bill);
			patient.setRoom(room);
			
			Bill bill1=new Bill();
			Room room1=new Room();
			Patient patient1=new Patient();
			bill1.setDate(LocalDate.of(2023,Month.DECEMBER,4));
			bill1.setAmount(12800);
			bill1.setStatus("Cleared"); 
			room1.setType("Intensive Care");
			room1.setStatus("Available");
		    patient1.setPname("Anil Dey");
	        patient1.setAddress("Arambagh");
	        patient1.setMobile("8282452397");
		    patient1.setDoctor(doctor);
		    patient1.setBill(bill1);
		    patient1.setRoom(room1);
			
			Bill bill2=new Bill();
			Room room2=new Room();
			Patient patient2=new Patient(); 
			bill2.setDate(LocalDate.of(2023,Month.SEPTEMBER,16));
			bill2.setAmount(40000);
			bill2.setStatus("Cleared"); 
			room2.setType("General");
			room2.setStatus("Available");
			patient2.setPname("Rashi Gupta");
            patient2.setAddress("Beleghata");
            patient2.setMobile("7439888017");
	        patient2.setDoctor(doctor1);
	        patient2.setBill(bill2);
	        patient2.setRoom(room2);
			
			Bill bill3=new Bill();
			Room room3=new Room();
			Patient patient3=new Patient();
			bill3.setDate(LocalDate.of(2024,Month.JANUARY,3));
			bill3.setAmount(20000);
			bill3.setStatus("Due");  	
			room3.setType("General");
			room3.setStatus("Occupied");
			patient3.setPname("Amit Kundu");
	        patient3.setAddress("Ranaghat");
	        patient3.setMobile("9653765100");
	        patient3.setDoctor(doctor1);
	        patient3.setBill(bill3);
	        patient3.setRoom(room3);
			
			Bill bill4=new Bill();
			Room room4=new Room();
			Patient patient4=new Patient();
			bill4.setDate(LocalDate.of(2023,Month.DECEMBER,31));
			bill4.setAmount(65000);
			bill4.setStatus("Due");  
			room4.setType("Intensive Care");
			room4.setStatus("Occupied");
	        patient4.setPname("Rai Saha");
	        patient4.setAddress("Siuri");
	        patient4.setMobile("7439576245");
	        patient4.setDoctor(doctor);
	        patient4.setBill(bill4);
	        patient4.setRoom(room4);
			
			Bill bill5=new Bill();
			Room room5=new Room();
			Patient patient5=new Patient();
			bill5.setDate(LocalDate.of(2023,Month.OCTOBER,12));
			bill5.setAmount(37300);
			bill5.setStatus("Cleared");
			room5.setType("Multibed Ward");
			room5.setStatus("Available");
	        patient5.setPname("Soham Sharma");
	        patient5.setAddress("Rajarhat");
	        patient5.setMobile("6352574501");
	        patient5.setDoctor(doctor2);
	        patient5.setBill(bill5);
	        patient5.setRoom(room5);
			
			Bill bill6=new Bill();
			Room room6=new Room();
			Patient patient6=new Patient();
			bill6.setDate(LocalDate.of(2024,Month.JANUARY,3));
			bill6.setAmount(22000);
			bill6.setStatus("Due");  
			room6.setType("Multibed Ward");
			room6.setStatus("Occupied");
	        patient6.setPname("Kirti Rai");
	        patient6.setAddress("Nalikul");
	        patient6.setMobile("6234869927");
	        patient6.setDoctor(doctor2);
	        patient6.setBill(bill6);
	        patient6.setRoom(room6);
			
			Bill bill7=new Bill();
			Room room7=new Room();
			Patient patient7=new Patient();
			bill7.setDate(LocalDate.of(2023,Month.DECEMBER,27));
			bill7.setAmount(15800);
			bill7.setStatus("Cleared");
			room7.setType("Oncology");
			room7.setStatus("Available");
	        patient7.setPname("Ashok Koli");
	        patient7.setAddress("Khidirpore");
	        patient7.setMobile("9651454502");
	        patient7.setDoctor(doctor3);
	        patient7.setBill(bill7); 
	        patient7.setRoom(room7);
			
			Bill bill8=new Bill();
			Room room8=new Room();
			Patient patient8=new Patient();
			bill8.setDate(LocalDate.of(2023,Month.OCTOBER,9));
			bill8.setAmount(7000);
			bill8.setStatus("Cleared"); 
			room8.setType("Single");
			room8.setStatus("Available");
	        patient8.setPname("Manoj Bera");
	        patient8.setAddress("Lalgola");
	        patient8.setMobile("6033861200");
	        patient8.setDoctor(doctor4);
	        patient8.setBill(bill8);
	        patient8.setRoom(room8);
			
			Bill bill9=new Bill();
			Room room9=new Room();
			Patient patient9=new Patient();
			bill9.setDate(LocalDate.of(2023,Month.DECEMBER,10));
			bill9.setAmount(10000);
			bill9.setStatus("Due");  
			room9.setType("Operating Suite");
			room9.setStatus("Occupied");
			patient9.setPname("Nishita Shaw");
	        patient9.setAddress("Barrackpore");
	        patient9.setMobile("7833987644");
	        patient9.setDoctor(doctor6);
	        patient9.setBill(bill9);
	        patient9.setRoom(room9);
			
			Bill bill10=new Bill();
			Room room10=new Room();
			Patient patient10=new Patient();
			bill10.setDate(LocalDate.of(2023,Month.DECEMBER,10));
			bill10.setAmount(10000);
			bill10.setStatus("Due"); 
			room10.setType("Operating Suite");
			room10.setStatus("Occupied");
			patient10.setPname("Abhishek Mitra");
	        patient10.setAddress("Kadamtala");
	        patient10.setMobile("8569440012");
	        patient10.setDoctor(doctor6);
	        patient10.setBill(bill10);
	        patient10.setRoom(room10);
			
			Bill bill11=new Bill();
			Room room11=new Room();
			Patient patient11=new Patient();
			bill11.setDate(LocalDate.of(2023,Month.DECEMBER,7));
			bill11.setAmount(30000);
			room11.setType("Maternity Care Patient Room");
			room11.setStatus("Available");
			bill11.setStatus("Cleared");  	       
			patient11.setPname("Arshi Banik");
	        patient11.setAddress("Dumdum");
	        patient11.setMobile("6297741230");
	        patient11.setDoctor(doctor5);
	        patient11.setBill(bill11);
	        patient11.setRoom(room11);
			  
			Bill bill12=new Bill();
			Room room12=new Room();
			Patient patient12=new Patient();
			bill12.setDate(LocalDate.of(2023,Month.DECEMBER,10));
			bill12.setAmount(10000);
			bill12.setStatus("Due");  
			room12.setType("Maternity Care Patient Room");
			room12.setStatus("Occupied");
			patient12.setPname("Tiyasha Basak");
	        patient12.setAddress("Andul");
	        patient12.setMobile("8356000636");
	        patient12.setDoctor(doctor5);
	        patient12.setBill(bill12);
	        patient12.setRoom(room12);
			
			Bill bill13=new Bill();
			Room room13=new Room();
			Patient patient13=new Patient();
			bill13.setDate(LocalDate.of(2023,Month.NOVEMBER,17));
			bill13.setAmount(18000);
			bill13.setStatus("Cleared");
			room13.setType("Maternity Care Patient Room");
			room13.setStatus("Available");
			patient13.setPname("Sonia Kumar");
	        patient13.setAddress("Sobhabazar");
	        patient13.setMobile("9767572200");
	        patient13.setDoctor(doctor5);
	        patient13.setBill(bill13); 
	        patient13.setRoom(room13);
			
			Bill bill14=new Bill();
			Room room14=new Room();
			Patient patient14=new Patient();
			bill14.setDate(LocalDate.of(2023,Month.DECEMBER,20));
			bill14.setAmount(5000);
			bill14.setStatus("Cleared");
			room14.setType("Single");
			room14.setStatus("Available");
			patient14.setPname("Nitya Chauhan");
	        patient14.setAddress("Park-Street");
	        patient14.setMobile("7689440158");
	        patient14.setDoctor(doctor3);
	        patient14.setBill(bill14); 
	        patient14.setRoom(room14);
	        
	        Bill bill15=new Bill();
	        Room room15=new Room();
			Patient patient15=new Patient();
			bill15.setDate(LocalDate.of(2024,Month.JANUARY,15));
			bill15.setAmount(12000);
			bill15.setStatus("Due");
			room15.setType("Paediatric Ward");
			room15.setStatus("Occupied");
			patient15.setPname("Trina Saha");
	        patient15.setAddress("Baguihati");
	        patient15.setMobile("9903345682");
	        patient15.setDoctor(doctor7);
	        patient15.setBill(bill15); 
	        patient15.setRoom(room15); 
     

	        doctor.getPatients().add(patient1);
	        doctor1.getPatients().add(patient2);
	        doctor1.getPatients().add(patient3);
	        doctor.getPatients().add(patient4);
	        doctor2.getPatients().add(patient5);
	        doctor2.getPatients().add(patient6);
	        doctor3.getPatients().add(patient7);
	        doctor4.getPatients().add(patient8);
	        doctor5.getPatients().add(patient11);
	        doctor6.getPatients().add(patient10);
	        doctor5.getPatients().add(patient12);
	        doctor5.getPatients().add(patient13);
	        doctor3.getPatients().add(patient14);
	        doctor6.getPatients().add(patient9);
	        doctor7.getPatients().add(patient15);    
	        session.save(patient);
	        session.save(patient1);
	        session.save(patient2);
	        session.save(patient3);
	        session.save(patient4);
	        session.save(patient5);
	        session.save(patient6);
	        session.save(patient7);
	        session.save(patient8);
	        session.save(patient9);
	        session.save(patient10);
	        session.save(patient11);
	        session.save(patient12);
	        session.save(patient13);
	        session.save(patient14);
	        session.save(patient15);
	        session.save(doctor);
	        session.save(doctor1);
	        session.save(doctor2); 
	        session.save(doctor3);
	        session.save(doctor4);
	        session.save(doctor5);
	        session.save(doctor6);
	        session.save(doctor7);
	        session.save(bill);
	        session.save(bill1);
	        session.save(bill2);
	        session.save(bill3);
	        session.save(bill4);
	        session.save(bill5);
	        session.save(bill6);
	        session.save(bill7);
	        session.save(bill8);
	        session.save(bill9);
	        session.save(bill10);
	        session.save(bill11);
	        session.save(bill12);
	        session.save(bill13);
	        session.save(bill14);
	        session.save(bill15);
	        session.save(room);
	        session.save(room1);
	        session.save(room2);
	        session.save(room3);
	        session.save(room4);
	        session.save(room5);
	        session.save(room6);
	        session.save(room7);
	        session.save(room8);
	        session.save(room9);
	        session.save(room10);
	        session.save(room11);
	        session.save(room12);
	        session.save(room13);
	        session.save(room14);
	        session.save(room15);
	        session.getTransaction().commit();
	        }
	        finally 
	        {
	        	session.close();
	        	sessionFactory.close();
	        }
    }
}

